// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehbytpvyihdouzpuvzsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoYnl0cHZ5aWhkb3V6cHV2enNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjUzODIsImV4cCI6MjA1ODAwMTM4Mn0.ODbqmOlQWDDtKvm_V7hEKR_MXctNjgrMhiYYEWxjjpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);